/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4db8205485005bf4a384dde745f1b629)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "WorkflowDO";
	}
	interface Env {
		ASSETS: Fetcher;
		TELEGRAM_BOT_TOKEN: string;
		OPENROUTER_API_KEY: string;
		WORKFLOW_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").WorkflowDO>;
	}
}
interface Env extends Cloudflare.Env {}
